# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Controller/'
            - '../src/Service/'
            - '../src/Event/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Event\Subscribers\PasswordSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber', connection: default}

    # Arguments for DeleteImageSubscriber
    App\Event\Subscribers\DeleteImageSubscriber:
        arguments:
            $uploadsPath: '%kernel.project_dir%/public/uploads'
        tags:
            - { name: 'doctrine.event_subscriber', connection: default }

    # Service for UploaderHelper
    App\Service\UploaderHelper:
        arguments:
            $uploadsPath: '%kernel.project_dir%/public/uploads'

    # Service for DeleteEntityObject
    App\Service\DeleteEntityObjectHelper:


    # Include sessions in DB
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(DATABASE_URL)%'
            - { db_table: 'customer_sessions' }